### PR TITLE
PhpUnit dist configuration to allow local machine configuration.

### PR DESCRIPTION
**Pull request by gpupo**
If phpunit.xml or phpunit.xml.dist (in that order) exist in the current working directory and --configuration is not used, the configuration will be automatically read from that file.

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Not sure I understand what this changes?

**Comment by Anahkiasen** [comment]
Well not what this changes but I mean, what is the goal here?

**Comment by gpupo** [comment]
A developer can create a file phpunit.xml different  from the default settings that is distributed.

phpunit.xml.dist -> versioned/distributed
phpunit.xml -> local computer only

**Comment by Anahkiasen** [comment]
Hm ok, well, sounds good

**Pull request merged**
