### PR TITLE
Support to use agent forwarding

### PR DESCRIPTION
**Pull request by montdidier**
These are changes to support agent forwarding linked with the following changes:

https://github.com/phpseclib/phpseclib/pull/518 change in phpseclib/phpseclib

https://github.com/illuminate/remote/pull/6 change in illuminate/remote

### CODE REVIEW

**Comment by Anahkiasen** [comment]
Newest PR is phpseclib/phpseclib#592 (posting this for reference)

**Comment by GrahamCampbell** [comment]
That pr is to phpseclib 2.0, so illuminate/remove will never support it.

**Comment by Anahkiasen** [comment]
Rocketeer 3.0 doesn't use illuminate/remote anymore, it uses phpseclib. With it being removed from L5 it didn't look like it was going to get much updating anyway (Envoy doesn't even use it) and Rocketeer wasn't using much of it anymore nowadays.

**Comment by montdidier** [comment]
So are we saying this PR will need updating when the phpseclib changes go through?

**Comment by Anahkiasen** [comment]
It'll probably need a quick rebase but apart from that changes look good

**Comment by ShonM** [comment]
Just a heads up I do have a working agent forwarding branch of Rocketeer and phpseclib together and am actively using it to deploy. It's a bit hacked up right now but I'm more than happy to have someone either copy it or I could submit a new PR :)

**Comment by vicdelfant** [comment]
@ShonM thanks a lot! We tried hacking it together ourselves but didn't quite succeed :)

**Comment by montdidier** [comment]
So my changes have finally been merged into phpseclib here https://github.com/phpseclib/phpseclib/pull/592. Apologies for the long wait. I don't know when the release is but we're getting there.

**Comment by ShonM** [comment]
This works on current master with those changes on phpseclib: https://github.com/ChessCom/rocketeer/commit/90bb89f01e68514fc448f6d5aed2355c88fdba5f

For a baseline example :)

**Comment by dinamic** [comment]
@montdidier, could you update us on the status of this feature?
The phpseclib PR has been marged back in March.

**Comment by adam-paterson** [comment]
@montdidier @Anahkiasen Any update on this? I'd love to get Rocketeer set up for the agencies deployments before I leave them in 4 weeks.

**Comment by WillBBP** [comment]
We are having the key based authentication problem which I think this issue is intended to fix.

E.g. 

    |---- Deploy/Clone (Clones a fresh instance of the repository by SCM)
    |===> Cloning repository in "/vagrant/project_name/releases/20160108134553"
    $ git clone "git@bitbucket.org:us/project_name.git" "/vagrant/project_name/releases/20160108134553" --branch="feature/rocketeer-deployment" --depth="1"
    [vagrant@project_name.vagrant] (vagrant) Initialized empty Git repository in /vagrant/project_name/releases/20160108134553/.git/
    [vagrant@project_name.vagrant] (vagrant) Warning: Permanently added the RSA host key for IP address '104.192.143.3' to the list of known hosts.
    [vagrant@project_name.vagrant] (vagrant) Permission denied (publickey).
    [vagrant@project_name.vagrant] (vagrant) fatal: The remote end hung up unexpectedly
    |===> An error occured: "Unable to clone the repository", while running:
    Initialized empty Git repository in /vagrant/project_name/releases/20160108134553/.git/
    Warning: Permanently added the RSA host key for IP address '104.192.143.3' to the list of known hosts.
    Permission denied (publickey).
    fatal: The remote end hung up unexpectedly

Running the same command direct in the vagrant box we are deploying to works just fine...

    git clone "git@bitbucket.org:us/project_name.git" "/vagrant/project_name/releases/20160108134553" --branch="feature/rocketeer-deployment" --depth="1

I saw somewhere mention of Rocketeer 3.0, does this have the fix already?

**Comment by montdidier** [comment]
Hi folks. I was most surprised to see this is still here. I am not up-to-date with why this didn't make yet but I'll attempt to make it happen shortly. @Anahkiasen Any pointers on what needs to happen here to get this going?

**Comment by TrentForshaw** [comment]
I need to see this merged in so I'm happy to help out where possible.

**Comment by aik099** [comment]
Seems, that @Anahkiasen is no longer actively maintaining the project because not much stuff gets merged in.

At least @montdidier can do a rebase to make this PR mergeable.

**Comment by Anahkiasen** [comment]
I'm rather busy but project is not abandoned, will take a look at the PRs as soon as I get some time

**Comment by aik099** [comment]
I see. Any estimates, when next release (what's in `dev-master` branch) will be made? Also I'm not quite sure what that release adds/changes except that it adds huge amount of traits, which IMO decreases readability of the code.

**Comment by Anahkiasen** [comment]
You mean `develop` no? master is the 2.x branch

**Comment by aik099** [comment]
Ah, sorry. Yes, I meant `dev-develop` branch.

**Comment by Anahkiasen** [comment]
Yeah I'm still unsure about the trait approach to Builders, but there are a good lot of other features on that branch though. Just, some of those are unfinished, preventing me from releasing R3

**Pull request closed without merging**
