### PR TITLE
Bump version constant

### PR DESCRIPTION
**Pull request by barryvdh**

### CODE REVIEW

**Comment by Anahkiasen** [comment]
GOD DAMMIT. KEEP FORGETTING. EVERY FUCKING TIME. ಠ_ಠ

**Comment by GrahamCampbell** [comment]
@Anahkiasen You might as well just remove it. Looks like a waste of time to me.

**Comment by GrahamCampbell** [comment]
People shouldn't really be writing version specific code relying on that constant. They should maintain separate codebases if that sort of thing is required.

**Comment by Anahkiasen** [comment]
It's passed to the console application class to display the version for. It'll be removed in 3.0 since the Box building process populates the version tag automatically but in 2.0 it's not done

**Pull request merged**
